/**
 * Email Service - Sends idea list and confirmation emails
 */

import nodemailer from 'nodemailer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..', '..');

// Create transporter
function createTransporter() {
    return nodemailer.createTransport({
        host: process.env.EMAIL_HOST || 'smtp.gmail.com',
        port: parseInt(process.env.EMAIL_PORT || '587'),
        secure: false,
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASS
        }
    });
}

/**
 * Send idea list email
 */
export async function sendIdeasEmail(ideas) {
    console.log('\n📧 Sending designs email...');

    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        console.log('   ⚠️ Email credentials not configured. Skipping email.');
        return { success: false, reason: 'No credentials' };
    }

    const recipient = process.env.RECIPIENT_EMAIL || 'shener1974@gmail.com';
    const generatedDir = path.join(rootDir, 'generated_images');
    const attachments = [];

    // Format HTML
    let html = `
    <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #f9f9fc; padding: 20px;">
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #1a1b1f; margin-bottom: 10px;">🎨 Your AI T-Shirt Designs</h1>
        <p style="color: #46464f;">Here are the designs generated based on your analysis.</p>
      </div>
  `;

    ideas.forEach((idea, i) => {
        const imageNum = String(i + 1).padStart(2, '0');
        const filename = `design_${imageNum}.png`;
        const filePath = path.join(generatedDir, filename);
        let imageHtml = '';

        if (fs.existsSync(filePath)) {
            attachments.push({
                filename: filename,
                path: filePath,
                cid: `design_${imageNum}` // same cid value as in the html img src
            });
            imageHtml = `<img src="cid:design_${imageNum}" alt="${idea.title}" style="width: 100%; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); display: block; margin: 0 auto;">`;
        } else {
            imageHtml = `<div style="width: 100%; height: 200px; background: #e5e4e9; display: flex; align-items: center; justify-content: center; border-radius: 12px; color: #76767f;">Image not found</div>`;
        }

        html += `
      <div style="background: #ffffff; padding: 20px; margin-bottom: 25px; border-radius: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
        <h2 style="color: #1a1b1f; margin-top: 0; font-size: 18px;">${i + 1}. ${idea.title}</h2>
        <div style="margin: 15px 0;">
          ${imageHtml}
        </div>
        <div style="color: #46464f; font-size: 14px;">
          <p><strong>🎯 Theme:</strong> ${idea.theme}</p>
          <p><strong>🎨 Style:</strong> ${idea.style}</p>
          <p><strong>🌈 Colors:</strong> ${idea.colorScheme}</p>
        </div>
      </div>
    `;
    });

    html += `
      <div style="text-align: center; margin-top: 30px; color: #76767f; font-size: 12px;">
        <p>Generated by Daily AI Images App</p>
      </div>
    </div>`;

    try {
        const transporter = createTransporter();
        await transporter.sendMail({
            from: process.env.EMAIL_USER,
            to: recipient,
            subject: `🎨 Your AI Designs - ${new Date().toLocaleDateString()}`,
            html: html,
            attachments: attachments
        });
        console.log(`   ✅ Designs email sent to ${recipient} with ${attachments.length} images`);
        return { success: true };
    } catch (error) {
        console.log(`   ❌ Failed to send email: ${error.message}`);
        return { success: false, error: error.message };
    }
}

/**
 * Send confirmation link email
 */
export async function sendConfirmationEmail() {
    console.log('\n📧 Sending confirmation email...');

    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        console.log('   ⚠️ Email credentials not configured. Skipping.');
        return { success: false, reason: 'No credentials' };
    }

    const recipient = process.env.RECIPIENT_EMAIL || 'shener1974@gmail.com';
    const baseUrl = process.env.BASE_URL || 'http://localhost:3000';
    const confirmUrl = `${baseUrl}/confirm`;

    const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; text-align: center;">
      <h1 style="color: #667eea;">🎉 Your Designs Are Ready!</h1>
      <p style="color: #666; font-size: 18px;">10 AI-generated T-shirt designs await your review.</p>
      <div style="margin: 30px 0;">
        <a href="${confirmUrl}" 
           style="display: inline-block; background: linear-gradient(135deg, #667eea, #764ba2); 
                  color: white; text-decoration: none; padding: 15px 40px; 
                  border-radius: 30px; font-size: 18px; font-weight: bold;">
          ✅ Confirm & View Designs
        </a>
      </div>
      <p style="color: #999; font-size: 14px;">Click the button above to review and publish your designs.</p>
    </div>
  `;

    try {
        const transporter = createTransporter();
        await transporter.sendMail({
            from: process.env.EMAIL_USER,
            to: recipient,
            subject: '🎉 Your T-Shirt Designs Are Ready - Confirm to Publish',
            html: html
        });
        console.log(`   ✅ Confirmation email sent to ${recipient}`);
        console.log(`   🔗 Confirmation URL: ${confirmUrl}`);
        return { success: true, confirmUrl };
    } catch (error) {
        console.log(`   ❌ Failed to send email: ${error.message}`);
        return { success: false, error: error.message };
    }
}

export default { sendIdeasEmail, sendConfirmationEmail };
